export const menu = [
  ['Property', '/property'],
  ['Services', '/services'],
  ['About', '/about'],
  ['Resources', '/resources'],
  ['Contact', '/contact'],
];

export const services = [
  [
    'Cryptocurrency',
    '/img/services/crypto.svg',
    'crypto',
    'Crypto classes, listing, minting',
    '7',
  ],
  [
    'Delivery',
    '/img/services/delivery.svg',
    'delivery',
    'Pos Malaysia, parcel delivery',
    'G',
  ],
  [
    'Food & Beverage',
    '/img/services/fnb.svg',
    'fnb',
    'Cafes, restaurants, fruit stands',
    'G, 1',
  ],
  [
    'Come On Tigers',
    '/img/services/come-on-tigers.png',
    'come-on-tigers',
    'Burgers, pizzas, fish & chips, rice set',
    'G (L1.102)',
    'https://www.facebook.com/comeontigersklcc?mibextid=ZbWKwL',
    'https://wa.me/60172059544',
  ],
  [
    'Offices',
    '/img/services/office.svg',
    'offices',
    'Accounting, legal, contractor, realtor',
    '4-10',
  ],
  [
    'Parking',
    '/img/services/parking.svg',
    'parking',
    'Season / day parking, valet service',
    'G, 2, 3',
  ],
  [
    'Printing',
    '/img/services/printing.svg',
    'printing',
    'Photocopy, color printing, banners, name cards, stamps',
    'G',
  ],
  [
    'Retail',
    '/img/services/retail.svg',
    'retail',
    'Clothing, groceries, hardware, jewelry, pharmacy, tailor',
    'G',
  ],
  ['Salons', '/img/services/salon.svg', 'salons', 'Hair and nail salons', 'G'],
  [
    'Security',
    '/img/services/security.svg',
    'security',
    'Building security',
    'G',
  ],
  [
    'Travel',
    '/img/services/travel.svg',
    'travel',
    'Tour, ticketing, car rental, travel insurance',
    '7',
  ],
];

export const prices = [
  [
    'Wisma Central',
    'https://goo.gl/maps/2pceQ9SAABhzo97u6',
    '/img/buildings/wisma-central.png',
    10,
    2000,
  ],
  [
    'KLCC Petronas Twin Tower',
    'https://goo.gl/maps/xk1VcruJdE4DDfHs7',
    '/img/buildings/klcc.png',
    15,
    5900,
  ],
  [
    'Four Seasons Hotel',
    'https://g.page/FourSeasonsKualaLumpur?share',
    '/img/buildings/four-seasons.png',
    14,
    4100,
  ],
  [
    'Bank of China (OSK Tower)',
    'https://goo.gl/maps/cN1R615dA1mZnQcZ6',
    '/img/buildings/osk.png',
    13,
    3800,
  ],
  [
    'Public Bank',
    'https://goo.gl/maps/K2tXaikbwHE4fgE77',
    '/img/buildings/public-bank.png',
    14,
    3800,
  ],
  [
    'Citibank Tower',
    'https://goo.gl/maps/zT4QstcBtNZ9B3Pw8',
    '/img/buildings/citibank.png',
    13,
    3800,
  ],
  [
    'Mandarin Oriental Hotel',
    'https://g.page/mandarin-oriental-kuala-lumpur?share',
    '/img/buildings/mandarin-oriental.png',
    14,
    4800,
  ],
  [
    'Axiata / Celcom Tower',
    'https://goo.gl/maps/BRxdY9DLzyXpvZtL7',
    '/img/buildings/axiata.png',
    13,
    4000,
  ],
  [
    'Maxis Tower',
    'https://goo.gl/maps/iB9An4quT4Fxw7Sp8',
    '/img/buildings/maxis-tower.png',
    15,
    5000,
  ],
  [
    'Oxley Towers / Sofi Hotel',
    'https://goo.gl/maps/m13T58ocRSxpjZk6A',
    '/img/buildings/oxley-towers.png',
    14,
    4800,
  ],
  [
    'Avenue K',
    'https://goo.gl/maps/xW8xo4GMJz4adGeX9',
    '/img/buildings/avenue-k.png',
    13,
    4500,
  ],
];

export const contacts = [
  [
    'Sales & Marketing',
    '/img/services/office.svg',
    'Mr. Albert',
    '+60173082891',
    'https://wa.me/60173082891',
  ],
  [
    'Security',
    '/img/services/security.svg',
    'Mr. Iman',
    '+60172507924',
    'https://wa.me/60172507924',
  ],
  [
    'Email',
    '/img/services/mail.svg',
    'Office',
    'contact@wismacentralkl.com',
    'mailto:contact@wismacentralkl.com',
  ],
];

export const resources = [
  [
    'Royal Oxford University',
    '/img/resources/rou.png',
    "Your partner in higher education. We specialize in business and we offer courses from diploma, bachelor's, MBA, to PhD. Online classes and scholarships are available.",
    'https://www.rou.education',
  ],
  [
    'travel88.net',
    '/img/resources/travel88.png',
    'One place for all your travel needs - airline ticketing, hotels, car rental, travel insurance, etc. Explore the most exclusive tour packages that take you around the world (literally), set foot on Anarctica, enjoy exotic spa and massages, as well as private therapeutic trips.',
    'https://travel88.net',
  ],
  [
    'Manpower Services',
    '/img/resources/workers.png',
    'We supply foregin workers, apply for work permits, and help process expired work visas.',
    'https://wa.me/60173082891',
  ],
  [
    'Reach Your Audience',
    '/img/resources/smm123.jpeg',
    'Automate your social media marketing with SMM123. Get free bulk messaging with our SMS servers.',
    'https://smm123.1university.com',
  ],
  [
    'Money News',
    '/img/resources/youtube.png',
    'Keep up to date on the latest topics on cryptocurrency, fiat economy and investment opportunities with Dr. Albert.',
    'https://www.youtube.com/@moneynews3772',
  ],
  [
    'Blockchain Services',
    '/img/services/crypto.svg',
    'Want to brush up your blockchain knowledge? Need help minting or listing a coin? Find us at L7.28C(B).',
    'https://wa.me/60173082891',
  ],
  [
    'Cryptocurrency Aggregator',
    '/img/resources/cbanks.png',
    'Track your favorite crypto prices, foreign exchange rate, as well as US stock performance at cbanks.org.',
    'https://www.cbanks.org',
  ],
  [
    'Trade Day and Night',
    '/img/resources/ampmcx.png',
    'Trade BTC, ETH, XRP, BNB, ITO, OTO and more at 0.1% fee at ampmcx.com.',
    'https://www.ampmcx.com',
  ],
  [
    'Your Ad Goes Here',
    '/img/services/office.svg',
    'Get your business listed today.',
    '/contact',
  ],
];
